version: "3"
services:
  grocy-companion:
    image: splendidwrx/grocycompanionmata:latest
    restart: always
    ports:
      - "9288:9288"
    environment:
      - CONFIG_PATH=/usr/src/app/config/config.ini
    networks:
      - grocy_campanion

networks:
  grocy_campanion:
